title: Rita Moura
email: ritabaptistademoura@gmail.com

baseurl: "/mysite" 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

description: "Hi! My name is Rita and this is my personal website. See my most recent work and get to know what I've been up to!"

collections:
  mybackground:
    output: true
    permalink: /mybackground/:path/
  myprojects:
    output: true
    permalink: /myprojects/:path/
  myotherprojects:
    output: true
    permalink: /myotherprojects/:path/
  mycontacts:
    output: true
    permalink: /mycontacts/:path